### ISSUE TITLE
How to pass user agent?

### ISSUE THREAD

**Issue by Mennaruuk** [amgedr/webchk#19]
Dear Amged,

I hope your health is well.

I would love to know how I can pass user agent using webchk. Different user agents may be necessary to visit some sites or get the appropriate status code.

Thank you so much.

**Comment by amgedr** [comment]
Hello,

I know there are some services that base their response on the client's user agent. Unfortunately, there is no way to set it at the moment, but I can add it in a few days.

**Comment by Mennaruuk** [comment]
Thank you very much, I really appreciate your help. Have a wonderful day.

P.S. I was reading webchk's [docs](https://webchk.readthedocs.io/_/downloads/en/latest/pdf/), and on page 7, it says that it can be imported into Python. How can I check for URLs with webchk inside of Python shell?

**Comment by amgedr** [comment]
Sorry, the current version is not importable. I moved a few things around and ended up breaking the API. I'm planning to fix it soon though.

**Comment by amgedr** [comment]
Just pushed the new version to PyPI. Please try it at your convenience.
