### ISSUE TITLE
cannot save output to a file

### ISSUE THREAD

**Issue by PaulSh84** [amgedr/webchk#5]
Windows 10 Enterprise 18.03
Steps: When I use **-o** argument, I am not getting the file created and ouput saved there.

` webchk -i list.txt -o test.txt`

Result: I am getting everything printed in console, but no file is created and no content is inserted there.
Please advise.

Thank you,
Paul

**Comment by thomasfaure3** [comment]
I dit that and it worked => webchk -i url.txt > some-descriptive-filename.txt

**Comment by PaulSh84** [comment]
> I dit that and it worked => webchk -i url.txt > some-descriptive-filename.txt

The question was about the argument **-o** which is described in ReadMe
  **-o OUTPUT, --output OUTPUT   Save output to a file**

This thing seems to be not working

**Comment by tech234a** [comment]
Yeah `--output` is broken for me too.
